// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pi_control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceAction int32

const (
	ServiceAction_START   ServiceAction = 0
	ServiceAction_STOP    ServiceAction = 1
	ServiceAction_RESTART ServiceAction = 2
	ServiceAction_ENABLE  ServiceAction = 3
	ServiceAction_DISABLE ServiceAction = 4
	ServiceAction_RELOAD  ServiceAction = 5
)

// Enum value maps for ServiceAction.
var (
	ServiceAction_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "RESTART",
		3: "ENABLE",
		4: "DISABLE",
		5: "RELOAD",
	}
	ServiceAction_value = map[string]int32{
		"START":   0,
		"STOP":    1,
		"RESTART": 2,
		"ENABLE":  3,
		"DISABLE": 4,
		"RELOAD":  5,
	}
)

func (x ServiceAction) Enum() *ServiceAction {
	p := new(ServiceAction)
	*p = x
	return p
}

func (x ServiceAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pi_control_proto_enumTypes[0].Descriptor()
}

func (ServiceAction) Type() protoreflect.EnumType {
	return &file_pi_control_proto_enumTypes[0]
}

func (x ServiceAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceAction.Descriptor instead.
func (ServiceAction) EnumDescriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pi_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{0}
}

// Real-time system statistics
type LiveStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU usage percentage (0-100)
	CpuUsage float64 `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// Per-core CPU usage
	CpuPerCore []float64 `protobuf:"fixed64,2,rep,packed,name=cpu_per_core,json=cpuPerCore,proto3" json:"cpu_per_core,omitempty"`
	// RAM usage in bytes
	RamUsed   uint64 `protobuf:"varint,3,opt,name=ram_used,json=ramUsed,proto3" json:"ram_used,omitempty"`
	RamTotal  uint64 `protobuf:"varint,4,opt,name=ram_total,json=ramTotal,proto3" json:"ram_total,omitempty"`
	RamFree   uint64 `protobuf:"varint,5,opt,name=ram_free,json=ramFree,proto3" json:"ram_free,omitempty"`
	RamCached uint64 `protobuf:"varint,6,opt,name=ram_cached,json=ramCached,proto3" json:"ram_cached,omitempty"`
	// Swap usage in bytes
	SwapUsed  uint64 `protobuf:"varint,7,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	SwapTotal uint64 `protobuf:"varint,8,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	// CPU temperature in Celsius
	CpuTemp float64 `protobuf:"fixed64,9,opt,name=cpu_temp,json=cpuTemp,proto3" json:"cpu_temp,omitempty"`
	// GPU temperature in Celsius (if available)
	GpuTemp float64 `protobuf:"fixed64,10,opt,name=gpu_temp,json=gpuTemp,proto3" json:"gpu_temp,omitempty"`
	// System uptime in seconds
	Uptime uint64 `protobuf:"varint,11,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Load averages
	Load_1Min  float64 `protobuf:"fixed64,12,opt,name=load_1min,json=load1min,proto3" json:"load_1min,omitempty"`
	Load_5Min  float64 `protobuf:"fixed64,13,opt,name=load_5min,json=load5min,proto3" json:"load_5min,omitempty"`
	Load_15Min float64 `protobuf:"fixed64,14,opt,name=load_15min,json=load15min,proto3" json:"load_15min,omitempty"`
	// Network stats (bytes per second)
	NetBytesSent uint64 `protobuf:"varint,15,opt,name=net_bytes_sent,json=netBytesSent,proto3" json:"net_bytes_sent,omitempty"`
	NetBytesRecv uint64 `protobuf:"varint,16,opt,name=net_bytes_recv,json=netBytesRecv,proto3" json:"net_bytes_recv,omitempty"`
	// Top processes by CPU usage
	TopProcesses []*ProcessInfo `protobuf:"bytes,17,rep,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"`
	// Timestamp of this stat snapshot
	Timestamp     int64 `protobuf:"varint,18,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveStats) Reset() {
	*x = LiveStats{}
	mi := &file_pi_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStats) ProtoMessage() {}

func (x *LiveStats) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStats.ProtoReflect.Descriptor instead.
func (*LiveStats) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{1}
}

func (x *LiveStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *LiveStats) GetCpuPerCore() []float64 {
	if x != nil {
		return x.CpuPerCore
	}
	return nil
}

func (x *LiveStats) GetRamUsed() uint64 {
	if x != nil {
		return x.RamUsed
	}
	return 0
}

func (x *LiveStats) GetRamTotal() uint64 {
	if x != nil {
		return x.RamTotal
	}
	return 0
}

func (x *LiveStats) GetRamFree() uint64 {
	if x != nil {
		return x.RamFree
	}
	return 0
}

func (x *LiveStats) GetRamCached() uint64 {
	if x != nil {
		return x.RamCached
	}
	return 0
}

func (x *LiveStats) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *LiveStats) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *LiveStats) GetCpuTemp() float64 {
	if x != nil {
		return x.CpuTemp
	}
	return 0
}

func (x *LiveStats) GetGpuTemp() float64 {
	if x != nil {
		return x.GpuTemp
	}
	return 0
}

func (x *LiveStats) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *LiveStats) GetLoad_1Min() float64 {
	if x != nil {
		return x.Load_1Min
	}
	return 0
}

func (x *LiveStats) GetLoad_5Min() float64 {
	if x != nil {
		return x.Load_5Min
	}
	return 0
}

func (x *LiveStats) GetLoad_15Min() float64 {
	if x != nil {
		return x.Load_15Min
	}
	return 0
}

func (x *LiveStats) GetNetBytesSent() uint64 {
	if x != nil {
		return x.NetBytesSent
	}
	return 0
}

func (x *LiveStats) GetNetBytesRecv() uint64 {
	if x != nil {
		return x.NetBytesRecv
	}
	return 0
}

func (x *LiveStats) GetTopProcesses() []*ProcessInfo {
	if x != nil {
		return x.TopProcesses
	}
	return nil
}

func (x *LiveStats) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Process information
type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Cmdline       string                 `protobuf:"bytes,8,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_pi_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ProcessInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProcessInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

// List of all processes
type ProcessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessList) Reset() {
	*x = ProcessList{}
	mi := &file_pi_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessList) ProtoMessage() {}

func (x *ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessList.ProtoReflect.Descriptor instead.
func (*ProcessList) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessList) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

// Process ID for kill operations
type ProcessId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessId) Reset() {
	*x = ProcessId{}
	mi := &file_pi_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessId) ProtoMessage() {}

func (x *ProcessId) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessId.ProtoReflect.Descriptor instead.
func (*ProcessId) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessId) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Service information
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active, inactive, failed, etc.
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SubState      string                 `protobuf:"bytes,5,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"` // running, dead, exited, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_pi_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceInfo) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

// List of all services
type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_pi_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceList) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

// Service control command
type ServiceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Action        ServiceAction          `protobuf:"varint,2,opt,name=action,proto3,enum=picontrol.ServiceAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCommand) Reset() {
	*x = ServiceCommand{}
	mi := &file_pi_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCommand) ProtoMessage() {}

func (x *ServiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCommand.ProtoReflect.Descriptor instead.
func (*ServiceCommand) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceCommand) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceCommand) GetAction() ServiceAction {
	if x != nil {
		return x.Action
	}
	return ServiceAction_START
}

// Generic action status response
type ActionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStatus) Reset() {
	*x = ActionStatus{}
	mi := &file_pi_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatus) ProtoMessage() {}

func (x *ActionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatus.ProtoReflect.Descriptor instead.
func (*ActionStatus) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{8}
}

func (x *ActionStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionStatus) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

// Log filter options
type LogFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by log level (empty = all)
	Levels []string `protobuf:"bytes,1,rep,name=levels,proto3" json:"levels,omitempty"` // error, warning, info, debug
	// Filter by service name (empty = all)
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// Number of past lines to include (0 = only new)
	TailLines     int32 `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFilter) Reset() {
	*x = LogFilter{}
	mi := &file_pi_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFilter) ProtoMessage() {}

func (x *LogFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFilter.ProtoReflect.Descriptor instead.
func (*LogFilter) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{9}
}

func (x *LogFilter) GetLevels() []string {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *LogFilter) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogFilter) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

// Single log entry
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pi_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{10}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Disk usage information
type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*DiskPartition       `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_pi_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{11}
}

func (x *DiskInfo) GetPartitions() []*DiskPartition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type DiskPartition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	MountPoint    string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Filesystem    string                 `protobuf:"bytes,3,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,6,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	UsagePercent  float64                `protobuf:"fixed64,7,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskPartition) Reset() {
	*x = DiskPartition{}
	mi := &file_pi_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskPartition) ProtoMessage() {}

func (x *DiskPartition) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskPartition.ProtoReflect.Descriptor instead.
func (*DiskPartition) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{12}
}

func (x *DiskPartition) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskPartition) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskPartition) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *DiskPartition) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskPartition) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskPartition) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *DiskPartition) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

// Network interface information
type NetworkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*NetworkInterface    `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_pi_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkInfo) GetInterfaces() []*NetworkInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IsUp          bool                   `protobuf:"varint,4,opt,name=is_up,json=isUp,proto3" json:"is_up,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,5,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,6,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	PacketsSent   uint64                 `protobuf:"varint,7,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRecv   uint64                 `protobuf:"varint,8,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_pi_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{14}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *NetworkInterface) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkInterface) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *NetworkInterface) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetworkInterface) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

// Network connection information
type NetworkConnectionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*NetworkConnection   `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConnectionList) Reset() {
	*x = NetworkConnectionList{}
	mi := &file_pi_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConnectionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConnectionList) ProtoMessage() {}

func (x *NetworkConnectionList) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConnectionList.ProtoReflect.Descriptor instead.
func (*NetworkConnectionList) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkConnectionList) GetConnections() []*NetworkConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type NetworkConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // TCP, UDP, etc.
	LocalAddress  string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	LocalPort     int32                  `protobuf:"varint,3,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemoteAddress string                 `protobuf:"bytes,4,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	RemotePort    int32                  `protobuf:"varint,5,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // ESTABLISHED, LISTEN, TIME_WAIT, etc.
	Pid           int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName   string                 `protobuf:"bytes,8,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConnection) Reset() {
	*x = NetworkConnection{}
	mi := &file_pi_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConnection) ProtoMessage() {}

func (x *NetworkConnection) ProtoReflect() protoreflect.Message {
	mi := &file_pi_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConnection.ProtoReflect.Descriptor instead.
func (*NetworkConnection) Descriptor() ([]byte, []int) {
	return file_pi_control_proto_rawDescGZIP(), []int{16}
}

func (x *NetworkConnection) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkConnection) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *NetworkConnection) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *NetworkConnection) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *NetworkConnection) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *NetworkConnection) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NetworkConnection) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NetworkConnection) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

var File_pi_control_proto protoreflect.FileDescriptor

const file_pi_control_proto_rawDesc = "" +
	"\n" +
	"\x10pi_control.proto\x12\tpicontrol\"\a\n" +
	"\x05Empty\"\xc6\x04\n" +
	"\tLiveStats\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12 \n" +
	"\fcpu_per_core\x18\x02 \x03(\x01R\n" +
	"cpuPerCore\x12\x19\n" +
	"\bram_used\x18\x03 \x01(\x04R\aramUsed\x12\x1b\n" +
	"\tram_total\x18\x04 \x01(\x04R\bramTotal\x12\x19\n" +
	"\bram_free\x18\x05 \x01(\x04R\aramFree\x12\x1d\n" +
	"\n" +
	"ram_cached\x18\x06 \x01(\x04R\tramCached\x12\x1b\n" +
	"\tswap_used\x18\a \x01(\x04R\bswapUsed\x12\x1d\n" +
	"\n" +
	"swap_total\x18\b \x01(\x04R\tswapTotal\x12\x19\n" +
	"\bcpu_temp\x18\t \x01(\x01R\acpuTemp\x12\x19\n" +
	"\bgpu_temp\x18\n" +
	" \x01(\x01R\agpuTemp\x12\x16\n" +
	"\x06uptime\x18\v \x01(\x04R\x06uptime\x12\x1b\n" +
	"\tload_1min\x18\f \x01(\x01R\bload1min\x12\x1b\n" +
	"\tload_5min\x18\r \x01(\x01R\bload5min\x12\x1d\n" +
	"\n" +
	"load_15min\x18\x0e \x01(\x01R\tload15min\x12$\n" +
	"\x0enet_bytes_sent\x18\x0f \x01(\x04R\fnetBytesSent\x12$\n" +
	"\x0enet_bytes_recv\x18\x10 \x01(\x04R\fnetBytesRecv\x12;\n" +
	"\rtop_processes\x18\x11 \x03(\v2\x16.picontrol.ProcessInfoR\ftopProcesses\x12\x1c\n" +
	"\ttimestamp\x18\x12 \x01(\x03R\ttimestamp\"\xec\x01\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x18\n" +
	"\acmdline\x18\b \x01(\tR\acmdline\"C\n" +
	"\vProcessList\x124\n" +
	"\tprocesses\x18\x01 \x03(\v2\x16.picontrol.ProcessInfoR\tprocesses\"\x1d\n" +
	"\tProcessId\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"\x92\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1b\n" +
	"\tsub_state\x18\x05 \x01(\tR\bsubState\"A\n" +
	"\vServiceList\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.picontrol.ServiceInfoR\bservices\"e\n" +
	"\x0eServiceCommand\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x120\n" +
	"\x06action\x18\x02 \x01(\x0e2\x18.picontrol.ServiceActionR\x06action\"a\n" +
	"\fActionStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode\"\\\n" +
	"\tLogFilter\x12\x16\n" +
	"\x06levels\x18\x01 \x03(\tR\x06levels\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\"r\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"D\n" +
	"\bDiskInfo\x128\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x18.picontrol.DiskPartitionR\n" +
	"partitions\"\xec\x01\n" +
	"\rDiskPartition\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x03 \x01(\tR\n" +
	"filesystem\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x06 \x01(\x04R\tfreeBytes\x12#\n" +
	"\rusage_percent\x18\a \x01(\x01R\fusagePercent\"J\n" +
	"\vNetworkInfo\x12;\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x1b.picontrol.NetworkInterfaceR\n" +
	"interfaces\"\xfe\x01\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x13\n" +
	"\x05is_up\x18\x04 \x01(\bR\x04isUp\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x05 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x06 \x01(\x04R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\a \x01(\x04R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\b \x01(\x04R\vpacketsRecv\"W\n" +
	"\x15NetworkConnectionList\x12>\n" +
	"\vconnections\x18\x01 \x03(\v2\x1c.picontrol.NetworkConnectionR\vconnections\"\x88\x02\n" +
	"\x11NetworkConnection\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12#\n" +
	"\rlocal_address\x18\x02 \x01(\tR\flocalAddress\x12\x1d\n" +
	"\n" +
	"local_port\x18\x03 \x01(\x05R\tlocalPort\x12%\n" +
	"\x0eremote_address\x18\x04 \x01(\tR\rremoteAddress\x12\x1f\n" +
	"\vremote_port\x18\x05 \x01(\x05R\n" +
	"remotePort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\b \x01(\tR\vprocessName*V\n" +
	"\rServiceAction\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\v\n" +
	"\aRESTART\x10\x02\x12\n" +
	"\n" +
	"\x06ENABLE\x10\x03\x12\v\n" +
	"\aDISABLE\x10\x04\x12\n" +
	"\n" +
	"\x06RELOAD\x10\x052\xba\x04\n" +
	"\rSystemMonitor\x127\n" +
	"\vStreamStats\x12\x10.picontrol.Empty\x1a\x14.picontrol.LiveStats0\x01\x129\n" +
	"\rListProcesses\x12\x10.picontrol.Empty\x1a\x16.picontrol.ProcessList\x12<\n" +
	"\vKillProcess\x12\x14.picontrol.ProcessId\x1a\x17.picontrol.ActionStatus\x128\n" +
	"\fListServices\x12\x10.picontrol.Empty\x1a\x16.picontrol.ServiceList\x12C\n" +
	"\rManageService\x12\x19.picontrol.ServiceCommand\x1a\x17.picontrol.ActionStatus\x129\n" +
	"\n" +
	"StreamLogs\x12\x14.picontrol.LogFilter\x1a\x13.picontrol.LogEntry0\x01\x124\n" +
	"\vGetDiskInfo\x12\x10.picontrol.Empty\x1a\x13.picontrol.DiskInfo\x12:\n" +
	"\x0eGetNetworkInfo\x12\x10.picontrol.Empty\x1a\x16.picontrol.NetworkInfo\x12K\n" +
	"\x15GetNetworkConnections\x12\x10.picontrol.Empty\x1a .picontrol.NetworkConnectionListB\x10Z\x0epi_agent/protob\x06proto3"

var (
	file_pi_control_proto_rawDescOnce sync.Once
	file_pi_control_proto_rawDescData []byte
)

func file_pi_control_proto_rawDescGZIP() []byte {
	file_pi_control_proto_rawDescOnce.Do(func() {
		file_pi_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pi_control_proto_rawDesc), len(file_pi_control_proto_rawDesc)))
	})
	return file_pi_control_proto_rawDescData
}

var file_pi_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pi_control_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pi_control_proto_goTypes = []any{
	(ServiceAction)(0),            // 0: picontrol.ServiceAction
	(*Empty)(nil),                 // 1: picontrol.Empty
	(*LiveStats)(nil),             // 2: picontrol.LiveStats
	(*ProcessInfo)(nil),           // 3: picontrol.ProcessInfo
	(*ProcessList)(nil),           // 4: picontrol.ProcessList
	(*ProcessId)(nil),             // 5: picontrol.ProcessId
	(*ServiceInfo)(nil),           // 6: picontrol.ServiceInfo
	(*ServiceList)(nil),           // 7: picontrol.ServiceList
	(*ServiceCommand)(nil),        // 8: picontrol.ServiceCommand
	(*ActionStatus)(nil),          // 9: picontrol.ActionStatus
	(*LogFilter)(nil),             // 10: picontrol.LogFilter
	(*LogEntry)(nil),              // 11: picontrol.LogEntry
	(*DiskInfo)(nil),              // 12: picontrol.DiskInfo
	(*DiskPartition)(nil),         // 13: picontrol.DiskPartition
	(*NetworkInfo)(nil),           // 14: picontrol.NetworkInfo
	(*NetworkInterface)(nil),      // 15: picontrol.NetworkInterface
	(*NetworkConnectionList)(nil), // 16: picontrol.NetworkConnectionList
	(*NetworkConnection)(nil),     // 17: picontrol.NetworkConnection
}
var file_pi_control_proto_depIdxs = []int32{
	3,  // 0: picontrol.LiveStats.top_processes:type_name -> picontrol.ProcessInfo
	3,  // 1: picontrol.ProcessList.processes:type_name -> picontrol.ProcessInfo
	6,  // 2: picontrol.ServiceList.services:type_name -> picontrol.ServiceInfo
	0,  // 3: picontrol.ServiceCommand.action:type_name -> picontrol.ServiceAction
	13, // 4: picontrol.DiskInfo.partitions:type_name -> picontrol.DiskPartition
	15, // 5: picontrol.NetworkInfo.interfaces:type_name -> picontrol.NetworkInterface
	17, // 6: picontrol.NetworkConnectionList.connections:type_name -> picontrol.NetworkConnection
	1,  // 7: picontrol.SystemMonitor.StreamStats:input_type -> picontrol.Empty
	1,  // 8: picontrol.SystemMonitor.ListProcesses:input_type -> picontrol.Empty
	5,  // 9: picontrol.SystemMonitor.KillProcess:input_type -> picontrol.ProcessId
	1,  // 10: picontrol.SystemMonitor.ListServices:input_type -> picontrol.Empty
	8,  // 11: picontrol.SystemMonitor.ManageService:input_type -> picontrol.ServiceCommand
	10, // 12: picontrol.SystemMonitor.StreamLogs:input_type -> picontrol.LogFilter
	1,  // 13: picontrol.SystemMonitor.GetDiskInfo:input_type -> picontrol.Empty
	1,  // 14: picontrol.SystemMonitor.GetNetworkInfo:input_type -> picontrol.Empty
	1,  // 15: picontrol.SystemMonitor.GetNetworkConnections:input_type -> picontrol.Empty
	2,  // 16: picontrol.SystemMonitor.StreamStats:output_type -> picontrol.LiveStats
	4,  // 17: picontrol.SystemMonitor.ListProcesses:output_type -> picontrol.ProcessList
	9,  // 18: picontrol.SystemMonitor.KillProcess:output_type -> picontrol.ActionStatus
	7,  // 19: picontrol.SystemMonitor.ListServices:output_type -> picontrol.ServiceList
	9,  // 20: picontrol.SystemMonitor.ManageService:output_type -> picontrol.ActionStatus
	11, // 21: picontrol.SystemMonitor.StreamLogs:output_type -> picontrol.LogEntry
	12, // 22: picontrol.SystemMonitor.GetDiskInfo:output_type -> picontrol.DiskInfo
	14, // 23: picontrol.SystemMonitor.GetNetworkInfo:output_type -> picontrol.NetworkInfo
	16, // 24: picontrol.SystemMonitor.GetNetworkConnections:output_type -> picontrol.NetworkConnectionList
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pi_control_proto_init() }
func file_pi_control_proto_init() {
	if File_pi_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pi_control_proto_rawDesc), len(file_pi_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pi_control_proto_goTypes,
		DependencyIndexes: file_pi_control_proto_depIdxs,
		EnumInfos:         file_pi_control_proto_enumTypes,
		MessageInfos:      file_pi_control_proto_msgTypes,
	}.Build()
	File_pi_control_proto = out.File
	file_pi_control_proto_goTypes = nil
	file_pi_control_proto_depIdxs = nil
}
