// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: pi_control.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemMonitor_StreamStats_FullMethodName            = "/picontrol.SystemMonitor/StreamStats"
	SystemMonitor_ListProcesses_FullMethodName          = "/picontrol.SystemMonitor/ListProcesses"
	SystemMonitor_KillProcess_FullMethodName            = "/picontrol.SystemMonitor/KillProcess"
	SystemMonitor_ListServices_FullMethodName           = "/picontrol.SystemMonitor/ListServices"
	SystemMonitor_ManageService_FullMethodName          = "/picontrol.SystemMonitor/ManageService"
	SystemMonitor_StreamLogs_FullMethodName             = "/picontrol.SystemMonitor/StreamLogs"
	SystemMonitor_GetDiskInfo_FullMethodName            = "/picontrol.SystemMonitor/GetDiskInfo"
	SystemMonitor_GetNetworkInfo_FullMethodName         = "/picontrol.SystemMonitor/GetNetworkInfo"
	SystemMonitor_GetNetworkConnections_FullMethodName  = "/picontrol.SystemMonitor/GetNetworkConnections"
	SystemMonitor_ListPackages_FullMethodName           = "/picontrol.SystemMonitor/ListPackages"
	SystemMonitor_InstallPackage_FullMethodName         = "/picontrol.SystemMonitor/InstallPackage"
	SystemMonitor_RemovePackage_FullMethodName          = "/picontrol.SystemMonitor/RemovePackage"
	SystemMonitor_UpdatePackage_FullMethodName          = "/picontrol.SystemMonitor/UpdatePackage"
	SystemMonitor_UpdatePackageList_FullMethodName      = "/picontrol.SystemMonitor/UpdatePackageList"
	SystemMonitor_UpgradePackages_FullMethodName        = "/picontrol.SystemMonitor/UpgradePackages"
	SystemMonitor_GetVersion_FullMethodName             = "/picontrol.SystemMonitor/GetVersion"
	SystemMonitor_GetPackageDetails_FullMethodName      = "/picontrol.SystemMonitor/GetPackageDetails"
	SystemMonitor_GetPackageDependencies_FullMethodName = "/picontrol.SystemMonitor/GetPackageDependencies"
	SystemMonitor_StreamPackageOperation_FullMethodName = "/picontrol.SystemMonitor/StreamPackageOperation"
	SystemMonitor_PingHost_FullMethodName               = "/picontrol.SystemMonitor/PingHost"
	SystemMonitor_ScanPorts_FullMethodName              = "/picontrol.SystemMonitor/ScanPorts"
	SystemMonitor_DNSLookup_FullMethodName              = "/picontrol.SystemMonitor/DNSLookup"
	SystemMonitor_Traceroute_FullMethodName             = "/picontrol.SystemMonitor/Traceroute"
	SystemMonitor_GetWifiInfo_FullMethodName            = "/picontrol.SystemMonitor/GetWifiInfo"
	SystemMonitor_TestNetworkSpeed_FullMethodName       = "/picontrol.SystemMonitor/TestNetworkSpeed"
	SystemMonitor_UploadFile_FullMethodName             = "/picontrol.SystemMonitor/UploadFile"
	SystemMonitor_DownloadFile_FullMethodName           = "/picontrol.SystemMonitor/DownloadFile"
	SystemMonitor_DeleteFile_FullMethodName             = "/picontrol.SystemMonitor/DeleteFile"
	SystemMonitor_GetSystemUpdateStatus_FullMethodName  = "/picontrol.SystemMonitor/GetSystemUpdateStatus"
	SystemMonitor_StreamSystemUpgrade_FullMethodName    = "/picontrol.SystemMonitor/StreamSystemUpgrade"
)

// SystemMonitorClient is the client API for SystemMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemMonitorClient interface {
	// Stream real-time system statistics (CPU, RAM, temp, etc.)
	StreamStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveStats], error)
	// Get list of all running processes
	ListProcesses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProcessList, error)
	// Kill a specific process by PID
	KillProcess(ctx context.Context, in *ProcessId, opts ...grpc.CallOption) (*ActionStatus, error)
	// List all systemd services
	ListServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceList, error)
	// Control a systemd service (start/stop/restart/enable/disable)
	ManageService(ctx context.Context, in *ServiceCommand, opts ...grpc.CallOption) (*ActionStatus, error)
	// Stream system logs in real-time
	StreamLogs(ctx context.Context, in *LogFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Get disk usage information
	GetDiskInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DiskInfo, error)
	// Get network interface information
	GetNetworkInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkInfo, error)
	// Get active network connections
	GetNetworkConnections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkConnectionList, error)
	// List installed packages (optionally filter)
	ListPackages(ctx context.Context, in *PackageFilter, opts ...grpc.CallOption) (*PackageList, error)
	// Install a package
	InstallPackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error)
	// Remove a package
	RemovePackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error)
	// Update a specific package
	UpdatePackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error)
	// Update package list (apt update)
	UpdatePackageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionStatus, error)
	// Upgrade packages (apt upgrade)
	UpgradePackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionStatus, error)
	// Get agent version
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionInfo, error)
	// Get detailed package information
	GetPackageDetails(ctx context.Context, in *PackageDetailsRequest, opts ...grpc.CallOption) (*PackageDetails, error)
	// Get package dependencies
	GetPackageDependencies(ctx context.Context, in *PackageDetailsRequest, opts ...grpc.CallOption) (*PackageDependencies, error)
	// Stream package operation logs (install/remove/update)
	StreamPackageOperation(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOperationLog], error)
	// Network Tools
	// Ping a host and stream results
	PingHost(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PingResponse], error)
	// Scan ports on a target host
	ScanPorts(ctx context.Context, in *PortScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortScanResponse], error)
	// DNS lookup
	DNSLookup(ctx context.Context, in *DNSRequest, opts ...grpc.CallOption) (*DNSResponse, error)
	// Traceroute to a host
	Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TracerouteResponse], error)
	// Get WiFi information
	GetWifiInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WifiInfo, error)
	// Test network speed (download/upload)
	TestNetworkSpeed(ctx context.Context, in *SpeedTestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpeedTestResponse], error)
	// File Transfer
	// Upload a file using streaming chunks
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileUploadResponse], error)
	// Download a file as streaming chunks
	DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// Delete a file or directory
	DeleteFile(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*FileDeleteResponse, error)
	// System Updates
	// Get system update status (OS info, kernel, upgradable packages)
	GetSystemUpdateStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemUpdateStatus, error)
	// Stream system upgrade progress (apt update + apt upgrade)
	StreamSystemUpgrade(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpgradeProgress], error)
}

type systemMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemMonitorClient(cc grpc.ClientConnInterface) SystemMonitorClient {
	return &systemMonitorClient{cc}
}

func (c *systemMonitorClient) StreamStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[0], SystemMonitor_StreamStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, LiveStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamStatsClient = grpc.ServerStreamingClient[LiveStats]

func (c *systemMonitorClient) ListProcesses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProcessList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessList)
	err := c.cc.Invoke(ctx, SystemMonitor_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) KillProcess(ctx context.Context, in *ProcessId, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) ListServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceList)
	err := c.cc.Invoke(ctx, SystemMonitor_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) ManageService(ctx context.Context, in *ServiceCommand, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_ManageService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) StreamLogs(ctx context.Context, in *LogFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[1], SystemMonitor_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogFilter, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *systemMonitorClient) GetDiskInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DiskInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiskInfo)
	err := c.cc.Invoke(ctx, SystemMonitor_GetDiskInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetNetworkInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkInfo)
	err := c.cc.Invoke(ctx, SystemMonitor_GetNetworkInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetNetworkConnections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkConnectionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkConnectionList)
	err := c.cc.Invoke(ctx, SystemMonitor_GetNetworkConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) ListPackages(ctx context.Context, in *PackageFilter, opts ...grpc.CallOption) (*PackageList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageList)
	err := c.cc.Invoke(ctx, SystemMonitor_ListPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) InstallPackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_InstallPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) RemovePackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_RemovePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) UpdatePackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_UpdatePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) UpdatePackageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_UpdatePackageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) UpgradePackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_UpgradePackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, SystemMonitor_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetPackageDetails(ctx context.Context, in *PackageDetailsRequest, opts ...grpc.CallOption) (*PackageDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageDetails)
	err := c.cc.Invoke(ctx, SystemMonitor_GetPackageDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetPackageDependencies(ctx context.Context, in *PackageDetailsRequest, opts ...grpc.CallOption) (*PackageDependencies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageDependencies)
	err := c.cc.Invoke(ctx, SystemMonitor_GetPackageDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) StreamPackageOperation(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOperationLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[2], SystemMonitor_StreamPackageOperation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageCommand, PackageOperationLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamPackageOperationClient = grpc.ServerStreamingClient[PackageOperationLog]

func (c *systemMonitorClient) PingHost(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[3], SystemMonitor_PingHost_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PingRequest, PingResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_PingHostClient = grpc.ServerStreamingClient[PingResponse]

func (c *systemMonitorClient) ScanPorts(ctx context.Context, in *PortScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[4], SystemMonitor_ScanPorts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PortScanRequest, PortScanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_ScanPortsClient = grpc.ServerStreamingClient[PortScanResponse]

func (c *systemMonitorClient) DNSLookup(ctx context.Context, in *DNSRequest, opts ...grpc.CallOption) (*DNSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSResponse)
	err := c.cc.Invoke(ctx, SystemMonitor_DNSLookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TracerouteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[5], SystemMonitor_Traceroute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TracerouteRequest, TracerouteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_TracerouteClient = grpc.ServerStreamingClient[TracerouteResponse]

func (c *systemMonitorClient) GetWifiInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WifiInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WifiInfo)
	err := c.cc.Invoke(ctx, SystemMonitor_GetWifiInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) TestNetworkSpeed(ctx context.Context, in *SpeedTestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpeedTestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[6], SystemMonitor_TestNetworkSpeed_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SpeedTestRequest, SpeedTestResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_TestNetworkSpeedClient = grpc.ServerStreamingClient[SpeedTestResponse]

func (c *systemMonitorClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, FileUploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[7], SystemMonitor_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, FileUploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_UploadFileClient = grpc.ClientStreamingClient[FileChunk, FileUploadResponse]

func (c *systemMonitorClient) DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[8], SystemMonitor_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileDownloadRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_DownloadFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *systemMonitorClient) DeleteFile(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*FileDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileDeleteResponse)
	err := c.cc.Invoke(ctx, SystemMonitor_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetSystemUpdateStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemUpdateStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemUpdateStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_GetSystemUpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) StreamSystemUpgrade(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpgradeProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[9], SystemMonitor_StreamSystemUpgrade_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, UpgradeProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamSystemUpgradeClient = grpc.ServerStreamingClient[UpgradeProgress]

// SystemMonitorServer is the server API for SystemMonitor service.
// All implementations must embed UnimplementedSystemMonitorServer
// for forward compatibility.
type SystemMonitorServer interface {
	// Stream real-time system statistics (CPU, RAM, temp, etc.)
	StreamStats(*Empty, grpc.ServerStreamingServer[LiveStats]) error
	// Get list of all running processes
	ListProcesses(context.Context, *Empty) (*ProcessList, error)
	// Kill a specific process by PID
	KillProcess(context.Context, *ProcessId) (*ActionStatus, error)
	// List all systemd services
	ListServices(context.Context, *Empty) (*ServiceList, error)
	// Control a systemd service (start/stop/restart/enable/disable)
	ManageService(context.Context, *ServiceCommand) (*ActionStatus, error)
	// Stream system logs in real-time
	StreamLogs(*LogFilter, grpc.ServerStreamingServer[LogEntry]) error
	// Get disk usage information
	GetDiskInfo(context.Context, *Empty) (*DiskInfo, error)
	// Get network interface information
	GetNetworkInfo(context.Context, *Empty) (*NetworkInfo, error)
	// Get active network connections
	GetNetworkConnections(context.Context, *Empty) (*NetworkConnectionList, error)
	// List installed packages (optionally filter)
	ListPackages(context.Context, *PackageFilter) (*PackageList, error)
	// Install a package
	InstallPackage(context.Context, *PackageCommand) (*ActionStatus, error)
	// Remove a package
	RemovePackage(context.Context, *PackageCommand) (*ActionStatus, error)
	// Update a specific package
	UpdatePackage(context.Context, *PackageCommand) (*ActionStatus, error)
	// Update package list (apt update)
	UpdatePackageList(context.Context, *Empty) (*ActionStatus, error)
	// Upgrade packages (apt upgrade)
	UpgradePackages(context.Context, *Empty) (*ActionStatus, error)
	// Get agent version
	GetVersion(context.Context, *Empty) (*VersionInfo, error)
	// Get detailed package information
	GetPackageDetails(context.Context, *PackageDetailsRequest) (*PackageDetails, error)
	// Get package dependencies
	GetPackageDependencies(context.Context, *PackageDetailsRequest) (*PackageDependencies, error)
	// Stream package operation logs (install/remove/update)
	StreamPackageOperation(*PackageCommand, grpc.ServerStreamingServer[PackageOperationLog]) error
	// Network Tools
	// Ping a host and stream results
	PingHost(*PingRequest, grpc.ServerStreamingServer[PingResponse]) error
	// Scan ports on a target host
	ScanPorts(*PortScanRequest, grpc.ServerStreamingServer[PortScanResponse]) error
	// DNS lookup
	DNSLookup(context.Context, *DNSRequest) (*DNSResponse, error)
	// Traceroute to a host
	Traceroute(*TracerouteRequest, grpc.ServerStreamingServer[TracerouteResponse]) error
	// Get WiFi information
	GetWifiInfo(context.Context, *Empty) (*WifiInfo, error)
	// Test network speed (download/upload)
	TestNetworkSpeed(*SpeedTestRequest, grpc.ServerStreamingServer[SpeedTestResponse]) error
	// File Transfer
	// Upload a file using streaming chunks
	UploadFile(grpc.ClientStreamingServer[FileChunk, FileUploadResponse]) error
	// Download a file as streaming chunks
	DownloadFile(*FileDownloadRequest, grpc.ServerStreamingServer[FileChunk]) error
	// Delete a file or directory
	DeleteFile(context.Context, *FileDeleteRequest) (*FileDeleteResponse, error)
	// System Updates
	// Get system update status (OS info, kernel, upgradable packages)
	GetSystemUpdateStatus(context.Context, *Empty) (*SystemUpdateStatus, error)
	// Stream system upgrade progress (apt update + apt upgrade)
	StreamSystemUpgrade(*Empty, grpc.ServerStreamingServer[UpgradeProgress]) error
	mustEmbedUnimplementedSystemMonitorServer()
}

// UnimplementedSystemMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemMonitorServer struct{}

func (UnimplementedSystemMonitorServer) StreamStats(*Empty, grpc.ServerStreamingServer[LiveStats]) error {
	return status.Error(codes.Unimplemented, "method StreamStats not implemented")
}
func (UnimplementedSystemMonitorServer) ListProcesses(context.Context, *Empty) (*ProcessList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedSystemMonitorServer) KillProcess(context.Context, *ProcessId) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedSystemMonitorServer) ListServices(context.Context, *Empty) (*ServiceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedSystemMonitorServer) ManageService(context.Context, *ServiceCommand) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ManageService not implemented")
}
func (UnimplementedSystemMonitorServer) StreamLogs(*LogFilter, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedSystemMonitorServer) GetDiskInfo(context.Context, *Empty) (*DiskInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiskInfo not implemented")
}
func (UnimplementedSystemMonitorServer) GetNetworkInfo(context.Context, *Empty) (*NetworkInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkInfo not implemented")
}
func (UnimplementedSystemMonitorServer) GetNetworkConnections(context.Context, *Empty) (*NetworkConnectionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkConnections not implemented")
}
func (UnimplementedSystemMonitorServer) ListPackages(context.Context, *PackageFilter) (*PackageList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedSystemMonitorServer) InstallPackage(context.Context, *PackageCommand) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallPackage not implemented")
}
func (UnimplementedSystemMonitorServer) RemovePackage(context.Context, *PackageCommand) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePackage not implemented")
}
func (UnimplementedSystemMonitorServer) UpdatePackage(context.Context, *PackageCommand) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePackage not implemented")
}
func (UnimplementedSystemMonitorServer) UpdatePackageList(context.Context, *Empty) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePackageList not implemented")
}
func (UnimplementedSystemMonitorServer) UpgradePackages(context.Context, *Empty) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradePackages not implemented")
}
func (UnimplementedSystemMonitorServer) GetVersion(context.Context, *Empty) (*VersionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedSystemMonitorServer) GetPackageDetails(context.Context, *PackageDetailsRequest) (*PackageDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageDetails not implemented")
}
func (UnimplementedSystemMonitorServer) GetPackageDependencies(context.Context, *PackageDetailsRequest) (*PackageDependencies, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageDependencies not implemented")
}
func (UnimplementedSystemMonitorServer) StreamPackageOperation(*PackageCommand, grpc.ServerStreamingServer[PackageOperationLog]) error {
	return status.Error(codes.Unimplemented, "method StreamPackageOperation not implemented")
}
func (UnimplementedSystemMonitorServer) PingHost(*PingRequest, grpc.ServerStreamingServer[PingResponse]) error {
	return status.Error(codes.Unimplemented, "method PingHost not implemented")
}
func (UnimplementedSystemMonitorServer) ScanPorts(*PortScanRequest, grpc.ServerStreamingServer[PortScanResponse]) error {
	return status.Error(codes.Unimplemented, "method ScanPorts not implemented")
}
func (UnimplementedSystemMonitorServer) DNSLookup(context.Context, *DNSRequest) (*DNSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DNSLookup not implemented")
}
func (UnimplementedSystemMonitorServer) Traceroute(*TracerouteRequest, grpc.ServerStreamingServer[TracerouteResponse]) error {
	return status.Error(codes.Unimplemented, "method Traceroute not implemented")
}
func (UnimplementedSystemMonitorServer) GetWifiInfo(context.Context, *Empty) (*WifiInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWifiInfo not implemented")
}
func (UnimplementedSystemMonitorServer) TestNetworkSpeed(*SpeedTestRequest, grpc.ServerStreamingServer[SpeedTestResponse]) error {
	return status.Error(codes.Unimplemented, "method TestNetworkSpeed not implemented")
}
func (UnimplementedSystemMonitorServer) UploadFile(grpc.ClientStreamingServer[FileChunk, FileUploadResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedSystemMonitorServer) DownloadFile(*FileDownloadRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedSystemMonitorServer) DeleteFile(context.Context, *FileDeleteRequest) (*FileDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedSystemMonitorServer) GetSystemUpdateStatus(context.Context, *Empty) (*SystemUpdateStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemUpdateStatus not implemented")
}
func (UnimplementedSystemMonitorServer) StreamSystemUpgrade(*Empty, grpc.ServerStreamingServer[UpgradeProgress]) error {
	return status.Error(codes.Unimplemented, "method StreamSystemUpgrade not implemented")
}
func (UnimplementedSystemMonitorServer) mustEmbedUnimplementedSystemMonitorServer() {}
func (UnimplementedSystemMonitorServer) testEmbeddedByValue()                       {}

// UnsafeSystemMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemMonitorServer will
// result in compilation errors.
type UnsafeSystemMonitorServer interface {
	mustEmbedUnimplementedSystemMonitorServer()
}

func RegisterSystemMonitorServer(s grpc.ServiceRegistrar, srv SystemMonitorServer) {
	// If the following call panics, it indicates UnimplementedSystemMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemMonitor_ServiceDesc, srv)
}

func _SystemMonitor_StreamStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).StreamStats(m, &grpc.GenericServerStream[Empty, LiveStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamStatsServer = grpc.ServerStreamingServer[LiveStats]

func _SystemMonitor_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).ListProcesses(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).KillProcess(ctx, req.(*ProcessId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).ListServices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_ManageService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).ManageService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_ManageService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).ManageService(ctx, req.(*ServiceCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).StreamLogs(m, &grpc.GenericServerStream[LogFilter, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _SystemMonitor_GetDiskInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetDiskInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetDiskInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetDiskInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetNetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetNetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetNetworkInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetNetworkInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetNetworkConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetNetworkConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetNetworkConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetNetworkConnections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_ListPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).ListPackages(ctx, req.(*PackageFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_InstallPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).InstallPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_InstallPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).InstallPackage(ctx, req.(*PackageCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_RemovePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).RemovePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_RemovePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).RemovePackage(ctx, req.(*PackageCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_UpdatePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).UpdatePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_UpdatePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).UpdatePackage(ctx, req.(*PackageCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_UpdatePackageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).UpdatePackageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_UpdatePackageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).UpdatePackageList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_UpgradePackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).UpgradePackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_UpgradePackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).UpgradePackages(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetPackageDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetPackageDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetPackageDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetPackageDetails(ctx, req.(*PackageDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetPackageDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetPackageDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetPackageDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetPackageDependencies(ctx, req.(*PackageDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_StreamPackageOperation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).StreamPackageOperation(m, &grpc.GenericServerStream[PackageCommand, PackageOperationLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamPackageOperationServer = grpc.ServerStreamingServer[PackageOperationLog]

func _SystemMonitor_PingHost_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).PingHost(m, &grpc.GenericServerStream[PingRequest, PingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_PingHostServer = grpc.ServerStreamingServer[PingResponse]

func _SystemMonitor_ScanPorts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PortScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).ScanPorts(m, &grpc.GenericServerStream[PortScanRequest, PortScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_ScanPortsServer = grpc.ServerStreamingServer[PortScanResponse]

func _SystemMonitor_DNSLookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).DNSLookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_DNSLookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).DNSLookup(ctx, req.(*DNSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_Traceroute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TracerouteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).Traceroute(m, &grpc.GenericServerStream[TracerouteRequest, TracerouteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_TracerouteServer = grpc.ServerStreamingServer[TracerouteResponse]

func _SystemMonitor_GetWifiInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetWifiInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetWifiInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetWifiInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_TestNetworkSpeed_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SpeedTestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).TestNetworkSpeed(m, &grpc.GenericServerStream[SpeedTestRequest, SpeedTestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_TestNetworkSpeedServer = grpc.ServerStreamingServer[SpeedTestResponse]

func _SystemMonitor_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SystemMonitorServer).UploadFile(&grpc.GenericServerStream[FileChunk, FileUploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_UploadFileServer = grpc.ClientStreamingServer[FileChunk, FileUploadResponse]

func _SystemMonitor_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).DownloadFile(m, &grpc.GenericServerStream[FileDownloadRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_DownloadFileServer = grpc.ServerStreamingServer[FileChunk]

func _SystemMonitor_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).DeleteFile(ctx, req.(*FileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetSystemUpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetSystemUpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetSystemUpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetSystemUpdateStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_StreamSystemUpgrade_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).StreamSystemUpgrade(m, &grpc.GenericServerStream[Empty, UpgradeProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamSystemUpgradeServer = grpc.ServerStreamingServer[UpgradeProgress]

// SystemMonitor_ServiceDesc is the grpc.ServiceDesc for SystemMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "picontrol.SystemMonitor",
	HandlerType: (*SystemMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProcesses",
			Handler:    _SystemMonitor_ListProcesses_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _SystemMonitor_KillProcess_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _SystemMonitor_ListServices_Handler,
		},
		{
			MethodName: "ManageService",
			Handler:    _SystemMonitor_ManageService_Handler,
		},
		{
			MethodName: "GetDiskInfo",
			Handler:    _SystemMonitor_GetDiskInfo_Handler,
		},
		{
			MethodName: "GetNetworkInfo",
			Handler:    _SystemMonitor_GetNetworkInfo_Handler,
		},
		{
			MethodName: "GetNetworkConnections",
			Handler:    _SystemMonitor_GetNetworkConnections_Handler,
		},
		{
			MethodName: "ListPackages",
			Handler:    _SystemMonitor_ListPackages_Handler,
		},
		{
			MethodName: "InstallPackage",
			Handler:    _SystemMonitor_InstallPackage_Handler,
		},
		{
			MethodName: "RemovePackage",
			Handler:    _SystemMonitor_RemovePackage_Handler,
		},
		{
			MethodName: "UpdatePackage",
			Handler:    _SystemMonitor_UpdatePackage_Handler,
		},
		{
			MethodName: "UpdatePackageList",
			Handler:    _SystemMonitor_UpdatePackageList_Handler,
		},
		{
			MethodName: "UpgradePackages",
			Handler:    _SystemMonitor_UpgradePackages_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SystemMonitor_GetVersion_Handler,
		},
		{
			MethodName: "GetPackageDetails",
			Handler:    _SystemMonitor_GetPackageDetails_Handler,
		},
		{
			MethodName: "GetPackageDependencies",
			Handler:    _SystemMonitor_GetPackageDependencies_Handler,
		},
		{
			MethodName: "DNSLookup",
			Handler:    _SystemMonitor_DNSLookup_Handler,
		},
		{
			MethodName: "GetWifiInfo",
			Handler:    _SystemMonitor_GetWifiInfo_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _SystemMonitor_DeleteFile_Handler,
		},
		{
			MethodName: "GetSystemUpdateStatus",
			Handler:    _SystemMonitor_GetSystemUpdateStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStats",
			Handler:       _SystemMonitor_StreamStats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _SystemMonitor_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPackageOperation",
			Handler:       _SystemMonitor_StreamPackageOperation_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PingHost",
			Handler:       _SystemMonitor_PingHost_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ScanPorts",
			Handler:       _SystemMonitor_ScanPorts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Traceroute",
			Handler:       _SystemMonitor_Traceroute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TestNetworkSpeed",
			Handler:       _SystemMonitor_TestNetworkSpeed_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _SystemMonitor_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _SystemMonitor_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSystemUpgrade",
			Handler:       _SystemMonitor_StreamSystemUpgrade_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pi_control.proto",
}

const (
	DockerService_ListContainers_FullMethodName   = "/picontrol.DockerService/ListContainers"
	DockerService_StartContainer_FullMethodName   = "/picontrol.DockerService/StartContainer"
	DockerService_StopContainer_FullMethodName    = "/picontrol.DockerService/StopContainer"
	DockerService_RestartContainer_FullMethodName = "/picontrol.DockerService/RestartContainer"
	DockerService_GetContainerLogs_FullMethodName = "/picontrol.DockerService/GetContainerLogs"
)

// DockerServiceClient is the client API for DockerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockerServiceClient interface {
	// List containers
	ListContainers(ctx context.Context, in *DockerFilter, opts ...grpc.CallOption) (*ContainerList, error)
	// Start a container
	StartContainer(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ActionStatus, error)
	// Stop a container
	StopContainer(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ActionStatus, error)
	// Restart a container
	RestartContainer(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ActionStatus, error)
	// Get container logs
	GetContainerLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
}

type dockerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerServiceClient(cc grpc.ClientConnInterface) DockerServiceClient {
	return &dockerServiceClient{cc}
}

func (c *dockerServiceClient) ListContainers(ctx context.Context, in *DockerFilter, opts ...grpc.CallOption) (*ContainerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainerList)
	err := c.cc.Invoke(ctx, DockerService_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) StartContainer(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, DockerService_StartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) StopContainer(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, DockerService_StopContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) RestartContainer(ctx context.Context, in *ContainerId, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, DockerService_RestartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerServiceClient) GetContainerLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DockerService_ServiceDesc.Streams[0], DockerService_GetContainerLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DockerService_GetContainerLogsClient = grpc.ServerStreamingClient[LogEntry]

// DockerServiceServer is the server API for DockerService service.
// All implementations must embed UnimplementedDockerServiceServer
// for forward compatibility.
type DockerServiceServer interface {
	// List containers
	ListContainers(context.Context, *DockerFilter) (*ContainerList, error)
	// Start a container
	StartContainer(context.Context, *ContainerId) (*ActionStatus, error)
	// Stop a container
	StopContainer(context.Context, *ContainerId) (*ActionStatus, error)
	// Restart a container
	RestartContainer(context.Context, *ContainerId) (*ActionStatus, error)
	// Get container logs
	GetContainerLogs(*LogRequest, grpc.ServerStreamingServer[LogEntry]) error
	mustEmbedUnimplementedDockerServiceServer()
}

// UnimplementedDockerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerServiceServer struct{}

func (UnimplementedDockerServiceServer) ListContainers(context.Context, *DockerFilter) (*ContainerList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedDockerServiceServer) StartContainer(context.Context, *ContainerId) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartContainer not implemented")
}
func (UnimplementedDockerServiceServer) StopContainer(context.Context, *ContainerId) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StopContainer not implemented")
}
func (UnimplementedDockerServiceServer) RestartContainer(context.Context, *ContainerId) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartContainer not implemented")
}
func (UnimplementedDockerServiceServer) GetContainerLogs(*LogRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method GetContainerLogs not implemented")
}
func (UnimplementedDockerServiceServer) mustEmbedUnimplementedDockerServiceServer() {}
func (UnimplementedDockerServiceServer) testEmbeddedByValue()                       {}

// UnsafeDockerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerServiceServer will
// result in compilation errors.
type UnsafeDockerServiceServer interface {
	mustEmbedUnimplementedDockerServiceServer()
}

func RegisterDockerServiceServer(s grpc.ServiceRegistrar, srv DockerServiceServer) {
	// If the following call panics, it indicates UnimplementedDockerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerService_ServiceDesc, srv)
}

func _DockerService_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).ListContainers(ctx, req.(*DockerFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_StartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).StartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_StartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).StartContainer(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_StopContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).StopContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_StopContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).StopContainer(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_RestartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServiceServer).RestartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerService_RestartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServiceServer).RestartContainer(ctx, req.(*ContainerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerService_GetContainerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DockerServiceServer).GetContainerLogs(m, &grpc.GenericServerStream[LogRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DockerService_GetContainerLogsServer = grpc.ServerStreamingServer[LogEntry]

// DockerService_ServiceDesc is the grpc.ServiceDesc for DockerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "picontrol.DockerService",
	HandlerType: (*DockerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContainers",
			Handler:    _DockerService_ListContainers_Handler,
		},
		{
			MethodName: "StartContainer",
			Handler:    _DockerService_StartContainer_Handler,
		},
		{
			MethodName: "StopContainer",
			Handler:    _DockerService_StopContainer_Handler,
		},
		{
			MethodName: "RestartContainer",
			Handler:    _DockerService_RestartContainer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContainerLogs",
			Handler:       _DockerService_GetContainerLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pi_control.proto",
}
