// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pi_control.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemMonitor_StreamStats_FullMethodName            = "/picontrol.SystemMonitor/StreamStats"
	SystemMonitor_ListProcesses_FullMethodName          = "/picontrol.SystemMonitor/ListProcesses"
	SystemMonitor_KillProcess_FullMethodName            = "/picontrol.SystemMonitor/KillProcess"
	SystemMonitor_ListServices_FullMethodName           = "/picontrol.SystemMonitor/ListServices"
	SystemMonitor_ManageService_FullMethodName          = "/picontrol.SystemMonitor/ManageService"
	SystemMonitor_StreamLogs_FullMethodName             = "/picontrol.SystemMonitor/StreamLogs"
	SystemMonitor_GetDiskInfo_FullMethodName            = "/picontrol.SystemMonitor/GetDiskInfo"
	SystemMonitor_GetNetworkInfo_FullMethodName         = "/picontrol.SystemMonitor/GetNetworkInfo"
	SystemMonitor_GetNetworkConnections_FullMethodName  = "/picontrol.SystemMonitor/GetNetworkConnections"
	SystemMonitor_ListPackages_FullMethodName           = "/picontrol.SystemMonitor/ListPackages"
	SystemMonitor_InstallPackage_FullMethodName         = "/picontrol.SystemMonitor/InstallPackage"
	SystemMonitor_RemovePackage_FullMethodName          = "/picontrol.SystemMonitor/RemovePackage"
	SystemMonitor_UpdatePackage_FullMethodName          = "/picontrol.SystemMonitor/UpdatePackage"
	SystemMonitor_UpdatePackageList_FullMethodName      = "/picontrol.SystemMonitor/UpdatePackageList"
	SystemMonitor_UpgradePackages_FullMethodName        = "/picontrol.SystemMonitor/UpgradePackages"
	SystemMonitor_GetVersion_FullMethodName             = "/picontrol.SystemMonitor/GetVersion"
	SystemMonitor_GetPackageDetails_FullMethodName      = "/picontrol.SystemMonitor/GetPackageDetails"
	SystemMonitor_GetPackageDependencies_FullMethodName = "/picontrol.SystemMonitor/GetPackageDependencies"
	SystemMonitor_StreamPackageOperation_FullMethodName = "/picontrol.SystemMonitor/StreamPackageOperation"
)

// SystemMonitorClient is the client API for SystemMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemMonitorClient interface {
	// Stream real-time system statistics (CPU, RAM, temp, etc.)
	StreamStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveStats], error)
	// Get list of all running processes
	ListProcesses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProcessList, error)
	// Kill a specific process by PID
	KillProcess(ctx context.Context, in *ProcessId, opts ...grpc.CallOption) (*ActionStatus, error)
	// List all systemd services
	ListServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceList, error)
	// Control a systemd service (start/stop/restart/enable/disable)
	ManageService(ctx context.Context, in *ServiceCommand, opts ...grpc.CallOption) (*ActionStatus, error)
	// Stream system logs in real-time
	StreamLogs(ctx context.Context, in *LogFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Get disk usage information
	GetDiskInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DiskInfo, error)
	// Get network interface information
	GetNetworkInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkInfo, error)
	// Get active network connections
	GetNetworkConnections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkConnectionList, error)
	// List installed packages (optionally filter)
	ListPackages(ctx context.Context, in *PackageFilter, opts ...grpc.CallOption) (*PackageList, error)
	// Install a package
	InstallPackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error)
	// Remove a package
	RemovePackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error)
	// Update a specific package
	UpdatePackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error)
	// Update package list (apt update)
	UpdatePackageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionStatus, error)
	// Upgrade packages (apt upgrade)
	UpgradePackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionStatus, error)
	// Get agent version
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionInfo, error)
	// Get detailed package information
	GetPackageDetails(ctx context.Context, in *PackageDetailsRequest, opts ...grpc.CallOption) (*PackageDetails, error)
	// Get package dependencies
	GetPackageDependencies(ctx context.Context, in *PackageDetailsRequest, opts ...grpc.CallOption) (*PackageDependencies, error)
	// Stream package operation logs (install/remove/update)
	StreamPackageOperation(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOperationLog], error)
}

type systemMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemMonitorClient(cc grpc.ClientConnInterface) SystemMonitorClient {
	return &systemMonitorClient{cc}
}

func (c *systemMonitorClient) StreamStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LiveStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[0], SystemMonitor_StreamStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, LiveStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamStatsClient = grpc.ServerStreamingClient[LiveStats]

func (c *systemMonitorClient) ListProcesses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProcessList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessList)
	err := c.cc.Invoke(ctx, SystemMonitor_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) KillProcess(ctx context.Context, in *ProcessId, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) ListServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceList)
	err := c.cc.Invoke(ctx, SystemMonitor_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) ManageService(ctx context.Context, in *ServiceCommand, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_ManageService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) StreamLogs(ctx context.Context, in *LogFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[1], SystemMonitor_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogFilter, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *systemMonitorClient) GetDiskInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DiskInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiskInfo)
	err := c.cc.Invoke(ctx, SystemMonitor_GetDiskInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetNetworkInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkInfo)
	err := c.cc.Invoke(ctx, SystemMonitor_GetNetworkInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetNetworkConnections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NetworkConnectionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkConnectionList)
	err := c.cc.Invoke(ctx, SystemMonitor_GetNetworkConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) ListPackages(ctx context.Context, in *PackageFilter, opts ...grpc.CallOption) (*PackageList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageList)
	err := c.cc.Invoke(ctx, SystemMonitor_ListPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) InstallPackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_InstallPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) RemovePackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_RemovePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) UpdatePackage(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_UpdatePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) UpdatePackageList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_UpdatePackageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) UpgradePackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, SystemMonitor_UpgradePackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, SystemMonitor_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetPackageDetails(ctx context.Context, in *PackageDetailsRequest, opts ...grpc.CallOption) (*PackageDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageDetails)
	err := c.cc.Invoke(ctx, SystemMonitor_GetPackageDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) GetPackageDependencies(ctx context.Context, in *PackageDetailsRequest, opts ...grpc.CallOption) (*PackageDependencies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageDependencies)
	err := c.cc.Invoke(ctx, SystemMonitor_GetPackageDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemMonitorClient) StreamPackageOperation(ctx context.Context, in *PackageCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOperationLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[2], SystemMonitor_StreamPackageOperation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageCommand, PackageOperationLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamPackageOperationClient = grpc.ServerStreamingClient[PackageOperationLog]

// SystemMonitorServer is the server API for SystemMonitor service.
// All implementations must embed UnimplementedSystemMonitorServer
// for forward compatibility.
type SystemMonitorServer interface {
	// Stream real-time system statistics (CPU, RAM, temp, etc.)
	StreamStats(*Empty, grpc.ServerStreamingServer[LiveStats]) error
	// Get list of all running processes
	ListProcesses(context.Context, *Empty) (*ProcessList, error)
	// Kill a specific process by PID
	KillProcess(context.Context, *ProcessId) (*ActionStatus, error)
	// List all systemd services
	ListServices(context.Context, *Empty) (*ServiceList, error)
	// Control a systemd service (start/stop/restart/enable/disable)
	ManageService(context.Context, *ServiceCommand) (*ActionStatus, error)
	// Stream system logs in real-time
	StreamLogs(*LogFilter, grpc.ServerStreamingServer[LogEntry]) error
	// Get disk usage information
	GetDiskInfo(context.Context, *Empty) (*DiskInfo, error)
	// Get network interface information
	GetNetworkInfo(context.Context, *Empty) (*NetworkInfo, error)
	// Get active network connections
	GetNetworkConnections(context.Context, *Empty) (*NetworkConnectionList, error)
	// List installed packages (optionally filter)
	ListPackages(context.Context, *PackageFilter) (*PackageList, error)
	// Install a package
	InstallPackage(context.Context, *PackageCommand) (*ActionStatus, error)
	// Remove a package
	RemovePackage(context.Context, *PackageCommand) (*ActionStatus, error)
	// Update a specific package
	UpdatePackage(context.Context, *PackageCommand) (*ActionStatus, error)
	// Update package list (apt update)
	UpdatePackageList(context.Context, *Empty) (*ActionStatus, error)
	// Upgrade packages (apt upgrade)
	UpgradePackages(context.Context, *Empty) (*ActionStatus, error)
	// Get agent version
	GetVersion(context.Context, *Empty) (*VersionInfo, error)
	// Get detailed package information
	GetPackageDetails(context.Context, *PackageDetailsRequest) (*PackageDetails, error)
	// Get package dependencies
	GetPackageDependencies(context.Context, *PackageDetailsRequest) (*PackageDependencies, error)
	// Stream package operation logs (install/remove/update)
	StreamPackageOperation(*PackageCommand, grpc.ServerStreamingServer[PackageOperationLog]) error
	mustEmbedUnimplementedSystemMonitorServer()
}

// UnimplementedSystemMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemMonitorServer struct{}

func (UnimplementedSystemMonitorServer) StreamStats(*Empty, grpc.ServerStreamingServer[LiveStats]) error {
	return status.Error(codes.Unimplemented, "method StreamStats not implemented")
}
func (UnimplementedSystemMonitorServer) ListProcesses(context.Context, *Empty) (*ProcessList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedSystemMonitorServer) KillProcess(context.Context, *ProcessId) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedSystemMonitorServer) ListServices(context.Context, *Empty) (*ServiceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedSystemMonitorServer) ManageService(context.Context, *ServiceCommand) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ManageService not implemented")
}
func (UnimplementedSystemMonitorServer) StreamLogs(*LogFilter, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedSystemMonitorServer) GetDiskInfo(context.Context, *Empty) (*DiskInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiskInfo not implemented")
}
func (UnimplementedSystemMonitorServer) GetNetworkInfo(context.Context, *Empty) (*NetworkInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkInfo not implemented")
}
func (UnimplementedSystemMonitorServer) GetNetworkConnections(context.Context, *Empty) (*NetworkConnectionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkConnections not implemented")
}
func (UnimplementedSystemMonitorServer) ListPackages(context.Context, *PackageFilter) (*PackageList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedSystemMonitorServer) InstallPackage(context.Context, *PackageCommand) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallPackage not implemented")
}
func (UnimplementedSystemMonitorServer) RemovePackage(context.Context, *PackageCommand) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePackage not implemented")
}
func (UnimplementedSystemMonitorServer) UpdatePackage(context.Context, *PackageCommand) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePackage not implemented")
}
func (UnimplementedSystemMonitorServer) UpdatePackageList(context.Context, *Empty) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePackageList not implemented")
}
func (UnimplementedSystemMonitorServer) UpgradePackages(context.Context, *Empty) (*ActionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradePackages not implemented")
}
func (UnimplementedSystemMonitorServer) GetVersion(context.Context, *Empty) (*VersionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedSystemMonitorServer) GetPackageDetails(context.Context, *PackageDetailsRequest) (*PackageDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageDetails not implemented")
}
func (UnimplementedSystemMonitorServer) GetPackageDependencies(context.Context, *PackageDetailsRequest) (*PackageDependencies, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPackageDependencies not implemented")
}
func (UnimplementedSystemMonitorServer) StreamPackageOperation(*PackageCommand, grpc.ServerStreamingServer[PackageOperationLog]) error {
	return status.Error(codes.Unimplemented, "method StreamPackageOperation not implemented")
}
func (UnimplementedSystemMonitorServer) mustEmbedUnimplementedSystemMonitorServer() {}
func (UnimplementedSystemMonitorServer) testEmbeddedByValue()                       {}

// UnsafeSystemMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemMonitorServer will
// result in compilation errors.
type UnsafeSystemMonitorServer interface {
	mustEmbedUnimplementedSystemMonitorServer()
}

func RegisterSystemMonitorServer(s grpc.ServiceRegistrar, srv SystemMonitorServer) {
	// If the following call panics, it indicates UnimplementedSystemMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemMonitor_ServiceDesc, srv)
}

func _SystemMonitor_StreamStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).StreamStats(m, &grpc.GenericServerStream[Empty, LiveStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamStatsServer = grpc.ServerStreamingServer[LiveStats]

func _SystemMonitor_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).ListProcesses(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).KillProcess(ctx, req.(*ProcessId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).ListServices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_ManageService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).ManageService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_ManageService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).ManageService(ctx, req.(*ServiceCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).StreamLogs(m, &grpc.GenericServerStream[LogFilter, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _SystemMonitor_GetDiskInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetDiskInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetDiskInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetDiskInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetNetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetNetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetNetworkInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetNetworkInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetNetworkConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetNetworkConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetNetworkConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetNetworkConnections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_ListPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).ListPackages(ctx, req.(*PackageFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_InstallPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).InstallPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_InstallPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).InstallPackage(ctx, req.(*PackageCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_RemovePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).RemovePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_RemovePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).RemovePackage(ctx, req.(*PackageCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_UpdatePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).UpdatePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_UpdatePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).UpdatePackage(ctx, req.(*PackageCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_UpdatePackageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).UpdatePackageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_UpdatePackageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).UpdatePackageList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_UpgradePackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).UpgradePackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_UpgradePackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).UpgradePackages(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetPackageDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetPackageDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetPackageDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetPackageDetails(ctx, req.(*PackageDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_GetPackageDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemMonitorServer).GetPackageDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemMonitor_GetPackageDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemMonitorServer).GetPackageDependencies(ctx, req.(*PackageDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemMonitor_StreamPackageOperation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitorServer).StreamPackageOperation(m, &grpc.GenericServerStream[PackageCommand, PackageOperationLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamPackageOperationServer = grpc.ServerStreamingServer[PackageOperationLog]

// SystemMonitor_ServiceDesc is the grpc.ServiceDesc for SystemMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "picontrol.SystemMonitor",
	HandlerType: (*SystemMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProcesses",
			Handler:    _SystemMonitor_ListProcesses_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _SystemMonitor_KillProcess_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _SystemMonitor_ListServices_Handler,
		},
		{
			MethodName: "ManageService",
			Handler:    _SystemMonitor_ManageService_Handler,
		},
		{
			MethodName: "GetDiskInfo",
			Handler:    _SystemMonitor_GetDiskInfo_Handler,
		},
		{
			MethodName: "GetNetworkInfo",
			Handler:    _SystemMonitor_GetNetworkInfo_Handler,
		},
		{
			MethodName: "GetNetworkConnections",
			Handler:    _SystemMonitor_GetNetworkConnections_Handler,
		},
		{
			MethodName: "ListPackages",
			Handler:    _SystemMonitor_ListPackages_Handler,
		},
		{
			MethodName: "InstallPackage",
			Handler:    _SystemMonitor_InstallPackage_Handler,
		},
		{
			MethodName: "RemovePackage",
			Handler:    _SystemMonitor_RemovePackage_Handler,
		},
		{
			MethodName: "UpdatePackage",
			Handler:    _SystemMonitor_UpdatePackage_Handler,
		},
		{
			MethodName: "UpdatePackageList",
			Handler:    _SystemMonitor_UpdatePackageList_Handler,
		},
		{
			MethodName: "UpgradePackages",
			Handler:    _SystemMonitor_UpgradePackages_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SystemMonitor_GetVersion_Handler,
		},
		{
			MethodName: "GetPackageDetails",
			Handler:    _SystemMonitor_GetPackageDetails_Handler,
		},
		{
			MethodName: "GetPackageDependencies",
			Handler:    _SystemMonitor_GetPackageDependencies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStats",
			Handler:       _SystemMonitor_StreamStats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _SystemMonitor_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPackageOperation",
			Handler:       _SystemMonitor_StreamPackageOperation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pi_control.proto",
}
